# Generated by Django 3.2.2 on 2021-05-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_count', models.IntegerField(default=1, verbose_name='商品數量')),
                ('total_price', models.IntegerField(default=0, verbose_name='商品總價')),
                ('order_status', models.SmallIntegerField(choices=[(1, '正在建立訂單'), (2, '店家出貨'), (3, '外送員領貨'), (4, '外送員抵達'), (5, '消費者領取貨(結束訂單)')], default=1, verbose_name='訂單狀態')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uber_eat.consumer')),
                ('deliver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uber_eat.deliver')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('transit_price', models.DecimalField(decimal_places=2, default='30', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('time', models.DateField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uber_eat.store')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1, verbose_name='商品數量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uber_eat.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uber_eat.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uber_eat.store'),
        ),
    ]
