# Generated by Django 3.2.2 on 2021-05-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber_eat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='address',
            new_name='Saddress',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='name',
            new_name='Sname',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='phone',
            new_name='Sphone',
        ),
    ]
