# Generated by Django 3.2.2 on 2021-05-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber_eat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='Cemail',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='Cpassword',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
