# Generated by Django 3.2.2 on 2021-05-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber_eat', '0002_auto_20210519_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='Sid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
