# Generated by Django 3.2.2 on 2021-05-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber_eat', '0002_auto_20210522_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Cid',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Did',
            new_name='D',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Sid',
            new_name='S',
        ),
        migrations.RenameField(
            model_name='ordergoods',
            old_name='Oid',
            new_name='O',
        ),
        migrations.RenameField(
            model_name='ordergoods',
            old_name='Pid',
            new_name='P',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Sid',
            new_name='S',
        ),
    ]
