# Generated by Django 3.2.2 on 2021-05-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber_eat', '0003_auto_20210522_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='consumer',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumer',
            name='password',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
