# Generated by Django 3.2.2 on 2021-05-24 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uber_eat', '0004_auto_20210522_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Oid', models.IntegerField(primary_key=True, serialize=False)),
                ('Ocount', models.IntegerField(default=0, verbose_name='商品數量')),
                ('Oprice', models.IntegerField(default=0, verbose_name='商品總價')),
                ('Ostatus', models.SmallIntegerField(choices=[(1, '正在建立訂單'), (2, '店家出貨'), (3, '外送員領貨'), (4, '外送員抵達'), (5, '消費者領取貨(結束訂單)')], default=1, verbose_name='訂單狀態')),
                ('Ocreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='email',
            new_name='Cemail',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='id',
            new_name='Cid',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='name',
            new_name='Cname',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='password',
            new_name='Cpassword',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='phone',
            new_name='Cphone',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Pprice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='store',
            new_name='S',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='enabled',
        ),
        migrations.AddField(
            model_name='store',
            name='Stransit_price',
            field=models.DecimalField(decimal_places=2, default='30', max_digits=10),
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('OGid', models.IntegerField(primary_key=True, serialize=False)),
                ('OGcount', models.IntegerField(default=1, verbose_name='商品數量')),
                ('O', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uber_eat.order')),
                ('P', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uber_eat.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='C',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uber_eat.consumer'),
        ),
        migrations.AddField(
            model_name='order',
            name='D',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uber_eat.deliver'),
        ),
        migrations.AddField(
            model_name='order',
            name='S',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uber_eat.store'),
        ),
    ]
